# Generated by Django 3.0.5 on 2020-04-08 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Author Name', max_length=20)),
                ('surname', models.CharField(help_text='Author Surname', max_length=20)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date Death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book Title', max_length=20)),
                ('isbn', models.CharField(help_text='Book ISBN', max_length=13)),
                ('description', models.TextField(help_text='Book Description', max_length=1000, verbose_name='Book Description')),
                ('author', models.ForeignKey(help_text='Book Author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert book category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert book language', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('date_of_return', models.DateField(blank=True, null=True, verbose_name='Date Return')),
                ('imprint', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('m', 'maintenance'), ('o', 'on loan'), ('a', 'available'), ('r', 'reserved')], default='m', help_text='Book Status', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book', verbose_name='Book title')),
                ('user', models.ForeignKey(blank=True, help_text='User', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_return'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='Book Categories', to='catalog.Category', verbose_name='Category'),
        ),
    ]
