# Generated by Django 3.0.5 on 2020-04-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Book Language', to='catalog.Language', verbose_name='Language'),
        ),
    ]
