# Generated by Django 3.0.5 on 2020-04-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={'ordering': ['date_of_return'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
