# Generated by Django 3.0.5 on 2020-04-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200412_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='Book Categories', null=True, to='catalog.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Book Language', null=True, to='catalog.Language', verbose_name='Language'),
        ),
    ]
